check file content md5
merico-dev/stream pull request #117
Opened 2022-01-07 08:06 UTC by lfbdev

## ⚠️ Pre-Checklist

Note: please complete **_ALL_** items in the following checklist, and **_remove this section before submitting_**.

- I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- This PR is using a `label` (bug, feature, etc.)
- My code has the necessary comments and documentation (if needed).
- I have added relevant tests
- I will remove this section (**⚠️ Pre-Checklist**) when submitting this PR

# Summary

## Key Points

- [ ] This is a breaking change.
- [ ] Documentation (new or existing) is updated.

## Description

Describe what this PR does and what problems it tries to solve in a few sentences.

### Related Issues

Will this PR close any open issues? If yes, would you please mention the issue(s) here?

### Current Behavior

Describe the current behavior of this issue, if relevant.

### New Behavior

Describe the newly updated behavior, if relevant.

### Screenshots

Include any relevant screenshots here.

### Other Information

Any other information that is important to this PR.

2022-01-07 08:17 UTC, IronCore864 commented on internal/pkg/pluginmanager/pbdownloader.go
> +	resp, err := pd.Get(downloadURL)
Check if we need to close the response.

2022-01-07 08:17 UTC, IronCore864 commented on internal/pkg/pluginmanager/manager.go
> +		if dup, _ := checkFileMD5(filepath.Join(pluginDir, pluginFileName), dc, pluginFileName, tool.Version); !dup {
Handle error.

2022-01-09 15:37 UTC, lfbdev commented on internal/pkg/pluginmanager/manager.go
> +		if dup, _ := checkFileMD5(filepath.Join(pluginDir, pluginFileName), dc, pluginFileName, tool.Version); !dup {
err check added

2022-01-09 15:37 UTC, lfbdev commented on internal/pkg/pluginmanager/pbdownloader.go
> +	resp, err := pd.Get(downloadURL)
add defer to close response conn

2022-01-10 02:02 UTC, IronCore864 approved these changes

2022-01-10 02:14 UTC, daniel-hutao requested changes
All feedbacks from me.

2022-01-10 02:14 UTC, daniel-hutao commented on internal/pkg/pluginmanager/manager.go
> +		if !dup {
if dup {
   log
   continue
}
code


let `if` shorter

2022-01-10 02:14 UTC, daniel-hutao commented on internal/pkg/pluginmanager/pbdownloader.go
> +	if resp != nil {
Maybe the `if` here is redundant

2022-01-10 02:50 UTC, daniel-hutao requested changes
2 tips added

2022-01-10 02:50 UTC, daniel-hutao commented on internal/pkg/pluginmanager/manager.go
> +		os.Remove(filepath.Join(pluginDir, pluginFileName))
error handle

2022-01-10 02:50 UTC, daniel-hutao commented on internal/pkg/pluginmanager/manager.go
> +	if strings.Compare(localmd5, remotemd5) == 0 {
It is usually clearer and always faster to use the built-in
// string comparison operators ==, <, >, and so on.

2022-01-10 03:02 UTC, daniel-hutao approved these changes

2022-01-10 03:02 UTC, daniel-hutao commented
/lgtm
/approve

2022-01-10 03:02 UTC, merged