Feat: Adding kube-prometheus plugin
merico-dev/stream pull request #134
Opened 2022-01-17 07:28 UTC by daniel-hutao

Signed-off-by: Daniel Hu <tao.hu@merico.dev>

# Summary

Adding kube-prometheus plugin

## Key Points

- [x] Documentation (new or existing) is updated.

2022-01-17 09:37 UTC, daniel-hutao commented
![image](https://user-images.githubusercontent.com/18692628/149744687-85a5cb17-441a-452f-b203-2f1fc12c99ad.png)

![image](https://user-images.githubusercontent.com/18692628/149744728-e7a420ba-4e88-4a79-8fee-d66c5b1d60df.png)

![image](https://user-images.githubusercontent.com/18692628/149744781-08839c6f-fb6e-424f-8564-e72fb995c312.png)

2022-01-17 09:38 UTC, daniel-hutao commented
![image](https://user-images.githubusercontent.com/18692628/149744992-4871c375-f92e-42d5-8235-845eb7e095c1.png)


![image](https://user-images.githubusercontent.com/18692628/149744951-dfd2f1b3-c9e3-40b3-850e-93f7f83b355b.png)

2022-01-18 01:27 UTC, IronCore864 requested changes

2022-01-18 01:27 UTC, IronCore864 commented on cmd/kubeprometheus/main.go
> +// Reinstall implements the installation of some GitHub Actions workflows.
The comment and the function name don't match; same below.

2022-01-18 01:57 UTC, lfbdev approved these changes
/lgtm

2022-01-18 01:58 UTC, IronCore864 approved these changes

2022-01-18 01:59 UTC, merged