trello state bugfix
merico-dev/stream pull request #225
Opened 2022-02-23 14:47 UTC by lfbdev

# Summary

## Description

1.  state file resource option: workflow dir lacks "/"
2. The board must be found in trello precisely, so we must get the boardid from state resource.
- if board found, list id(todo/doing/done) can be queried

2022-02-23 15:42 UTC, daniel-hutao requested changes

2022-02-24 01:27 UTC, IronCore864 commented on examples/config.yaml
> +      ident: trello-github-integ-golang-demo
What does ident mean here? Ident normally means identification; does it mean identification here? Is the word used by Trello official doc so we use the abbreviation？More comments in the readme of this plugin would help.

2022-02-24 02:12 UTC, IronCore864 requested changes

2022-02-24 02:12 UTC, IronCore864 commented on pkg/util/trello/trello.go
> +	smgr, err := statemanager.NewManager(b)
Plugins should be state-agnostic.

2022-02-24 08:54 UTC, IronCore864 commented on docs/plugins/trello-github-integ_plugin.md
> +_Trello board description managed by DevStream, don't modify it_
Trello board description “is” managed by DevStream, please don't modify it.

Missing "is"; add "please" to be more polite; and missing period at the end.

2022-02-24 08:55 UTC, IronCore864 commented on pkg/util/trello/trello.go
> +				log.Errorf("Unknown lists format: len==%d", len(lists))
Missing period at the end of the log.

2022-02-24 08:57 UTC, IronCore864 commented on pkg/util/trello/trello.go
> +	return fmt.Sprintf("Description managed by DevStream,don't change.%s/%s", owner, repo)
"Description is managed by DevStream, please don't modify. %s/%s"

or simply

"Managed by DevStream, please don't modify. %s/%s"

- There should be a space after punctuation.
- change -> modify (to be consistent with the readme)
- add "please"

2022-02-24 08:57 UTC, IronCore864 approved these changes

2022-02-24 11:51 UTC, daniel-hutao approved these changes

2022-02-24 12:28 UTC, merged