refactor(github): decouple trellogithub and "github.com/google/go-git…
merico-dev/stream pull request #311
Opened 2022-03-12 16:46 UTC by warren830

# Summary

move Repositories.getContents to pkg/util/github to decouple  trellogithub and "github.com/google/go-github/v42/github"

## Key Points

- [ ] This is a breaking change.
- [ ] Documentation (new or existing) is updated.

## Description

Describe what this PR does and what problems it tries to solve in a few sentences.

### Related Issues

closes #307

### Current Behavior

Describe the current behavior of this issue, if relevant.

### New Behavior

Describe the newly updated behavior, if relevant.

### Screenshots

Include any relevant screenshots here.

### Other Information

Any other information that is important to this PR.

2022-03-13 05:28 UTC, daniel-hutao commented on internal/pkg/plugin/trellogithub/github.go
> +	"github.com/spf13/viper"
```go
 	"github.com/spf13/viper"

	"github.com/merico-dev/stream/pkg/util/github"
 	"github.com/merico-dev/stream/pkg/util/log"
 	"github.com/merico-dev/stream/pkg/util/mapz"
```

2022-03-13 05:29 UTC, daniel-hutao commented on pkg/util/github/github.go
> +	github "github.com/google/go-github/v42/github"
"github.com/google/go-github/v42/github"

2022-03-13 05:37 UTC, daniel-hutao commented on internal/pkg/plugin/trellogithub/github.go
>  func (tg *TrelloGithub) FetchRemoteContent(wsFiles []string) ([]string, map[string]error, error) {
It's better to sink this function into `util/github` package.

2022-03-13 05:38 UTC, daniel-hutao commented on internal/pkg/plugin/trellogithub/github.go
>  func (tg *TrelloGithub) GetWorkflowPath() (string, error) {
It's better to sink this function into `util/github` package.

2022-03-13 05:41 UTC, daniel-hutao commented
@warren830 Thanks for your pr, you did a good job with decouple.

However, the operation of github in the `trellogithub` package is still too complicated. This kind of complex logic should be encapsulated in `util/github` package. Otherwise, `util/github` will have no advantage over the `native github` package.

2022-03-13 12:49 UTC, daniel-hutao commented
@warren830 I saw your update; thank you for giving up your time off over the weekend to continue contributing. But there are still some problems, such as:

- internal/pkg/plugin/trellogithub/github.go

```go
	"github.com/merico-dev/stream/pkg/util/github"
 	"github.com/spf13/viper"
```

should be

```go
 	"github.com/spf13/viper"

	"github.com/merico-dev/stream/pkg/util/github"
```

- internal/pkg/plugin/trellogithub/helper.go

```go
	"github.com/merico-dev/stream/pkg/util/github"
 	"github.com/merico-dev/stream/pkg/util/trello"
 	"github.com/mitchellh/mapstructure"
```

should be 

```go
 	"github.com/mitchellh/mapstructure"

	"github.com/merico-dev/stream/pkg/util/github"
 	"github.com/merico-dev/stream/pkg/util/trello"
```

- pkg/util/github/github.go

```go
	"github.com/merico-dev/stream/pkg/util/log"
 	"github.com/merico-dev/stream/pkg/util/mapz"
 	"golang.org/x/oauth2"
```

should be 

```go
 	"golang.org/x/oauth2"

	"github.com/merico-dev/stream/pkg/util/log"
 	"github.com/merico-dev/stream/pkg/util/mapz"
```

See the fmt stage in Makefile(`make fmt`) for more info.

2022-03-13 13:21 UTC, daniel-hutao commented on pkg/util/github/github.go
> +	_, dirContent, resp, err := client.Repositories.GetContents(
The client is `nil` here. You shouldn't use the `client` directly here, but put this code into a client method, something like: 

```go
func (c *Client) FetchRemoteContent(){c.XXX()}
```

2022-03-13 13:23 UTC, daniel-hutao requested changes
See the comment above.

Please don't rush and complete the refactoring slowly. Please test it after writing the code to make sure it works. After the test is passed, welcome to continue call me anytime. Thanks again for your hard work.

2022-03-14 01:30 UTC, IronCore864 commented
> @warren830 I saw your new commit; Thank you for taking the time to submit contributions over the weekend.
> 
> But there are still some problems, such as:
> 
>     * internal/pkg/plugin/trellogithub/github.go
> 
> 
> ```go
> 	"github.com/merico-dev/stream/pkg/util/github"
>  	"github.com/spf13/viper"
> ```
> 
> should be
> 
> ```go
>  	"github.com/spf13/viper"
> 
> 	"github.com/merico-dev/stream/pkg/util/github"
> ```
> 
>     * internal/pkg/plugin/trellogithub/helper.go
> 
> 
> ```go
> 	"github.com/merico-dev/stream/pkg/util/github"
>  	"github.com/merico-dev/stream/pkg/util/trello"
>  	"github.com/mitchellh/mapstructure"
> ```
> 
> should be
> 
> ```go
>  	"github.com/mitchellh/mapstructure"
> 
> 	"github.com/merico-dev/stream/pkg/util/github"
>  	"github.com/merico-dev/stream/pkg/util/trello"
> ```
> 
>     * pkg/util/github/github.go
> 
> 
> ```go
> 	"github.com/merico-dev/stream/pkg/util/log"
>  	"github.com/merico-dev/stream/pkg/util/mapz"
>  	"golang.org/x/oauth2"
> ```
> 
> should be
> 
> ```go
>  	"golang.org/x/oauth2"
> 
> 	"github.com/merico-dev/stream/pkg/util/log"
>  	"github.com/merico-dev/stream/pkg/util/mapz"
> ```
> 
> See the fmt stage in Makefile(`make fmt`) for more info.

This is the standard against which all future imports order will be measured.

A big thumbs-up to Daniel!

2022-03-14 09:15 UTC, IronCore864 approved these changes

2022-03-15 06:45 UTC, daniel-hutao approved these changes

2022-03-15 06:45 UTC, merged