doc: Plugins Documentation
merico-dev/stream pull request #44
Opened 2021-12-21 03:05 UTC by IronCore864

# Summary

## Key Points

- [ ] This is a breaking change.
- [x] Documentation (new or existing) is updated.

## Description

Plugins documentation updated:

- how to create a plugin
- doc for GitHub Actions plugin
- doc for ArgoCD plugin
- doc for ArgoCD App plugin

### Related Issues

https://github.com/merico-dev/stream/issues/6

2021-12-21 03:35 UTC, IronCore864 commented
@lfbdev @daniel-hutao, please help to review this change.

Please pay close attention to grammar, syntax, the example usage, and the comments in it.

You can commit directly to this branch when you find a bug.

Merge and delete the branch after reviewing is done. Thanks.

2021-12-21 03:35 UTC, IronCore864 commented
Feel free to enrich the content, too.

2021-12-22 03:34 UTC, daniel-hutao requested changes
done

2021-12-22 03:34 UTC, daniel-hutao commented on docs/argocd_app_plugin.md
> +  # Checkout the version from the GitHub releases.
We could change "Checkout" to lowercase "checkout" to keep it consistent with the previous comment.

2021-12-22 03:46 UTC, daniel-hutao commented on docs/argocd_app_plugin.md
> +  # Checkout the version from the GitHub releases.
#51

2021-12-22 03:46 UTC, daniel-hutao commented
/lgtm

2021-12-22 06:31 UTC, merged